# Form implementation generated from reading ui file 'c:\Users\mllin\OneDrive\Documents\GitHub\Shuriken_lite\ui\Mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.repoInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.repoInput.setObjectName("repoInput")
        self.verticalLayout.addWidget(self.repoInput)
        self.browseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout.addWidget(self.browseButton)
        self.buildButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buildButton.setObjectName("buildButton")
        self.verticalLayout.addWidget(self.buildButton)
        self.packageButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.packageButton.setObjectName("packageButton")
        self.verticalLayout.addWidget(self.packageButton)
        self.logOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.logOutput.setObjectName("logOutput")
        self.verticalLayout.addWidget(self.logOutput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shuriken Lite"))
        self.titleLabel.setText(_translate("MainWindow", "Shuriken Lite Builder"))
        self.repoInput.setPlaceholderText(_translate("MainWindow", "Source folder path..."))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.buildButton.setText(_translate("MainWindow", "Build"))
        self.packageButton.setText(_translate("MainWindow", "Package Installer"))
        self.logOutput.setPlaceholderText(_translate("MainWindow", "Build and packaging logs..."))
